name: Drugs
author: castletinou & PrototypeS1
main: fr.castletinou.plugin.Main
version: 1.0
commands:
  drugs:
    description: Give custom potion
    permission: drugs.use
    permission-message: You do not have permission :/
    usage: ยง4/drugs <drugsName>
    aliases: dr